### ISSUE TITLE
AttributeError: module 'aws_cdk' has no attribute 'cx_api' on `cdk deploy`

### ISSUE THREAD

**Issue by febriy** [aws-samples/aws-serverless-cicd-workshop#85]
I'm following the instructions within https://cicd.serverlessworkshops.io/python/buildpipe/cdkinit.html
This is what I get on `cdk deploy`:

```
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from aws_cdk import aws_lambda
  File "/home/ec2-user/environment/sam-app/pipeline/.venv/lib64/python3.7/site-packages/aws_cdk/__init__.py", line 21690, in <module>
    from . import aws_acmpca
  File "/home/ec2-user/environment/sam-app/pipeline/.venv/lib64/python3.7/site-packages/aws_cdk/aws_acmpca/__init__.py", line 79, in <module>
    from ._jsii import *
  File "/home/ec2-user/environment/sam-app/pipeline/.venv/lib64/python3.7/site-packages/aws_cdk/aws_acmpca/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.core._jsii
  File "/home/ec2-user/environment/sam-app/pipeline/.venv/lib64/python3.7/site-packages/aws_cdk/core/__init__.py", line 6371, in <module>
    class ConstructNode(metaclass=jsii.JSIIMeta, jsii_type="@aws-cdk/core.ConstructNode"):
  File "/home/ec2-user/environment/sam-app/pipeline/.venv/lib64/python3.7/site-packages/aws_cdk/core/__init__.py", line 6553, in ConstructNode
    runtime_info: typing.Optional[aws_cdk.cx_api.RuntimeInfo] = None,
AttributeError: module 'aws_cdk' has no attribute 'cx_api'
```

python version: Python 3.7.10
cdk version: 2.2.0 (build 4f5c27c)

**Comment by febriy** [comment]
I've managed to continue with CDK V1 installed
Would need to refactor the code to V2 in the future

**Comment by AlperSakarya** [comment]
@febriy how did you manage to continue with the V1 while following the steps?
Even after removing 2.x and dropping down to 1.143.0, I still get the same 'aws_cdk' has no attribute 'cx_api' error


```

(.venv) ConsoleAdmin:~/environment/sam-app/pipeline (main) $ cdk --version
2.10.0 (build e5b301f)

(.venv) ConsoleAdmin:~/environment/sam-app/pipeline (main) $ npm remove -g aws-cdk@2.x                                                             
up to date in 0.04s

(.venv) ConsoleAdmin:~/environment/sam-app/pipeline (main) $ npm install -g aws-cdk@1.x
/home/ec2-user/.nvm/versions/node/v14.19.0/bin/cdk -> /home/ec2-user/.nvm/versions/node/v14.19.0/lib/node_modules/aws-cdk/bin/cdk
+ aws-cdk@1.143.0
updated 7 packages in 4.218s

(.venv) ConsoleAdmin:~/environment/sam-app/pipeline (main) $ cdk --version
1.143.0 (build bebd295)
```

**Comment by brianz** [comment]
This workshop has been reorganized to use SAM Pipelines rather than CDK.

If you are still looking for a CDK reference you can find a working version [in the Appendix section](https://cicd.serverlessworkshops.io/appendix.html).
